### ISSUE TITLE
Calling specific url with query parameters and authorization jwt token (for example express application)

### ISSUE THREAD

**Issue by mutasemhidmi** [alexcasalboni/aws-lambda-power-tuning#125]
I'm using the below payload to call specific url in a deployed lambda function note that i'm using sam to deploy a whole web application into lambda so all the routing is inside the application, so is it possible to use this tool to test thanks

{
  "queryParams": {
    "page": "0",
    "pageSize": "10"
  },
 "headers": {
    "Authorization": "Bearer eyJraWQiOiIwUWNUUyt....."
  },
 "method": "GET",
 "url": "https://BASEURL/hello"
}

**Comment by alexcasalboni** [comment]
Hey @mutasemhidmi you can find out more about the Lambda + API Gateway proxy integration here: https://docs.aws.amazon.com/apigateway/api-reference/resource/integration/

Also, check out how you are implementing routing inside your Lambda function handler. Do you use a `url` event parameter there?

**Comment by mutasemhidmi** [comment]
I'm using quarkus framework and deploying it using sam CLI, so i'm using the framework inner routing is it possible just to call a specific URL inside my application?

**Comment by alexcasalboni** [comment]
@mutasemhidmi did you try to execute this Lambda function locally? ([docs here](https://quarkus.io/guides/amazon-lambda))

Do you have a local `payload.json` file that corresponds to the expected payload for this function?

The full integration structure is documented here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

So it should be the `rawPath` parameter (instead of `url`), and without the base url (i.e. without protocol, host, and prefix).

**Comment by alexcasalboni** [comment]
Closing for now. Please reopen this if the problem occurs again.
