### ISSUE TITLE
QUESTION: Is there similar tool for Cloud Functions?

### ISSUE THREAD

**Issue by jfbaro** [alexcasalboni/aws-lambda-power-tuning#160]
Congrats on the great work. I have used this for AWS Lambda, but now I am working for a new organization and they are on GCP. Any help would be appreciated. Thanks

**Comment by alexcasalboni** [comment]
Hi @jfbaro 👋  thanks for using Lambda Power Tuning 🙏 

I'm not too familiar with GCP personally, but I'd guess it should be possible to build something similar with Google Cloud Workflows and Google Cloud Functions. Or even with a simple local script invoking the Cloud Functions APIs.

In order to work, the Cloud Functions APIs need the ability to:
- change power/RAM on the fly
- inspect invocation logs/stats immediately after the invocation is completed
- configure multiple versions/aliases with different memory configurations, and then invoke them in parallel (if you care about parallel execution of the workflow -> very useful if you care about overall speed of execution)

If these conditions are met, and if you narrow down the tuning features/integrations (e.g. no need to integrate S3 or pre/post hooks), you should be able to reuse some of the tuning business logic by reimplementing some of the `lambda/utils.js` utility functions (where the largest majority of AWS API calls are implemented).

**Comment by jfbaro** [comment]
Thanks for the reply. I'll investigate this and get back here once I have an answer! Glad that the solution seems to be portable.

**Comment by alexcasalboni** [comment]
Closing this for now.

Please feel free to reopen if you want to continue the conversation and/or share your results :)

**Comment by gideongrinberg** [comment]
@jfbaro did you ever manage to work this out? As far as I can tell, there's no way to change the resources of a CF on the fly.
