### ISSUE TITLE
Make Node.js 10.x runtime an option

### ISSUE THREAD

**Issue by Tudes** [alexcasalboni/aws-lambda-power-tuning#24]
As of May 15 2019 AWS added support for Node.js 10.x in Lambdas. I'm thinking it would be nice to have an option to run the `power-tuning` Lambdas in a similar Runtime as the Lambda someone is writing.

Link to article [AWS What's new](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/)

**Comment by alexcasalboni** [comment]
Hi @Tudes,

Thanks for opening this :)

Can you please clarify a bit? I don't understand how running the `power-tuning` functions in a different runtime would be a benefit.

If the function I'm tuning is written in Go or .NET, the `power-tuning` functions don't have to be implemented in Go or .NET.

Of course I understand why you'd want to use Node.js 10.x instead of 8.10, and I've also planned to refactor my Node.js code to use async/await and some of the new ES6 syntactic sugar. But I don't understand the point of making the runtime customizable as a CloudFormation parameter.

**Comment by alexcasalboni** [comment]
Closed this, as the ES6 refactor is now completed and parametrizing the state machine functions runtime doesn't really add any value for users of this tool.
