### ISSUE TITLE
Cannot add memory option

### ISSUE THREAD

**Issue by theburningmonk** [alexcasalboni/aws-lambda-power-tuning#35]
When I deployed via the console, I added a 2048MB option to the comma-separated list:

![image](https://user-images.githubusercontent.com/546969/62717727-ba50be00-ba04-11e9-9c89-24982f54f32a.png)

But the state machine doesn't reflect this:

![image](https://user-images.githubusercontent.com/546969/62717874-fd129600-ba04-11e9-8ac3-d1cdf9bb3afc.png)

Is it suppose to work? (thought you were doing something along the line of deploying a custom resource and then using it in the same stack, like what SLS does for event bridge)

**Comment by alexcasalboni** [comment]
Hi Yan,

This used to be available because you could generate the state machine
dynamically as a pre-deployment step.

In order to simplify the overall  experience and the state machine
reprentation, I’ve made the state machine static. Now it contains the most
common memory configurations that you may want to test, but not all. In the
general case, I wouldn’t recommend testing all configurations, but in some
specific cases it could make sense.

If you want to add more configurations, you’d need to fork the repo, modify
the state machine in the yaml template, and deploy manually.

I’m looking forward to updating the project to allow for dynamic
configurations as inputs without complicating everything else.

Let me know if you need help with the yaml definition (it’s an inlined
string).

**Comment by theburningmonk** [comment]
I see. That's fine, I manually edited the definition in the console, but thought I could configure it since it's presented as a parameter.

No worries!

**Comment by alexcasalboni** [comment]
Ok, cool.

Right now you can configure it to test only a subset of the branches. But adding new ones requires editing the state machine.

I'm looking into nested workflows to make the whole thing easier. Will keep you posted!
