### ISSUE TITLE
Reset $LATEST memory configuration after state machine execution

### ISSUE THREAD

**Issue by devsatishm** [alexcasalboni/aws-lambda-power-tuning#36]
@alexcasalboni  Great job on the tool, very handy & useful!

I ran the test on my lambda function with all possible memory settings. Initially, my function had 512MB memory assigned. After the tests were completed (confirmed that `Cleaner` & `Finalizer` are green), function got assigned memory of 3008 MB.  I also checked that the versions that got created during the test were removed (which is expected) but the memory got set to the max memory given during the tests. 

Is this expected?

Thanks!

**Comment by alexcasalboni** [comment]
Hi @devsatishm, thanks for using the tool :)

I confirm that the state machine operates on the `$LATEST` version of your function. More in detail, it does the following:

1. Set memory to `X` (version `$LATEST`)
2. Publish new version (version `N`)
3. Create new alias `XMB` and binds it to version `N`
4. Runs all executions in parallel using aliases
5. Deletes all versions and aliases

As as result (undocumented, sorry), the state machine leaves the default `$LATEST` version to the maximum memory value created in the initial state.

I can see how this is not ideal, although you are the first one to report it so far :)

Would you expect the state machine to simply reset the `$LATEST` version the its initial memory configuration?

Alternatively, this could be configurable so that the clean up state will set `$LATEST` to either the initial value or the optimal value (which is handy for CI/CD use cases). 

What do you think?

**Comment by alexcasalboni** [comment]
Makes sense.

Ok, I should be able to work on this in the next couple of week.

In the meantime - and in general when working with Lambda - I'd recommend using an alias instead of `$LATEST` when you setup integrations. This allows you to keep working on `$LATEST` without breaking production.

**Comment by alexcasalboni** [comment]
Update: this is now implemented :)

I'll be publishing on SAR too later this week.
