### ISSUE TITLE
--dry-run

### ISSUE THREAD

**Issue by pavelloz** [alexcasalboni/aws-lambda-power-tuning#41]
Per discussion in https://github.com/alexcasalboni/aws-lambda-power-tuning/issues/37#issuecomment-537992823

This might be an overkill, because `num=1` would cover it, but having a possibility to verify if user's setup is correct could benefit a lot of people.

I personally always run dry runs if they exist, especially when im a beginner in an area, and/or stakes of mistake is high.

**Comment by alexcasalboni** [comment]
My thoughts:


- I'd expect a dry-run to be as cheap as possible, but in order to test the setup we'd need at least `num=1`
- I'd expect a dry-run to ignore the value of `num` and always use `num=1` to make the state machine execution cheap & fast  
- I'd expect a dry-run to ignore `strategy` and disable the analyzer (i.e. no optimal-config output)
- I'd expect a dry-run to disable the visualization URL
- I'd expect a dry-run to disable auto-tuning


Anything else to consider?

**Comment by alexcasalboni** [comment]
Merged and published on SAR as v3.2.3 :)
