### ISSUE TITLE
API Gateway end-to-end testing?

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#55]
How could we support this?

Would it be mutually exclusive wrt Lambda or maybe a totally independent branch?

APIGW comes with many configurations that might make performance tuning less reliable such as caching, WAF, endpoint type (regional or edge-optimized), etc.

We could simply invoke the API endpoint instead of the Lambda function, but I'm not 100% sure of what the benefit would be.

**Comment by simonfrey** [comment]
Don't think API gateway end-end testing is the next important step.

IMO the next step would be to allow to test more than one function per run and optimize them together.

E.g. maybe it is better to have function 1 run a bit longer but be cheaper by not giving it more memory and function 2 gets a lot more memory because overall the both function tied together would be cheaper in total with that strategy.

**Comment by alexcasalboni** [comment]
@simonfrey thanks for sharing this!

Would you mind opening another issue and expanding a bit? So far the tool assumes functions can be optimized independently - but intuitively I can imagine a scenario where function A is invoking function B and you want to optimize both at the same time. I'd argue that you can probably achieve optimal numbers by optimizing them independently, but let's dive deeper :)

**Comment by alexcasalboni** [comment]
Closing for now.
