### ISSUE TITLE
"The execution failed (check execution logs)" -- where are the logs? 

### ISSUE THREAD

**Issue by jcollum** [alexcasalboni/aws-lambda-power-tuning#58]
I don't see a logs folder of any kind. Nor a recently created text file. I'm hunting around in the CLI docs, maybe that's where the answer is but it would be very helpful to have some sort of hint in the execution output here...

**Comment by alexcasalboni** [comment]
Hi @jcollum, there is nothing stored locally, you are right.

You can retrieve "logs" by inspecting the [execution history](https://docs.aws.amazon.com/cli/latest/reference/stepfunctions/get-execution-history.html) via API:

```bash
aws stepfunctions get-execution-history --execution-arn $EXECUTION_ARN
```

I didn't include this command in the `execute.sh` script because its ouput is quite verbose. Maybe I could include a hint about the command though.

Let me know if this is helpful.

**Comment by jcollum** [comment]
That helped, thanks.
