### ISSUE TITLE
Is correct the relation between RAM Configuration/Cost by ms?

### ISSUE THREAD

**Issue by Sojer23** [alexcasalboni/aws-lambda-power-tuning#75]
Hi Alex!

After some testing with the tool I have seen incorrect numbers on the graph. 

I have compared the time/costs results of one lambda execution in my region (EU-Ireland) with the result that appears hover the graph. And...

Here my calculation:

1. Data from AWS Lambda Pricing (EU-Ireland):
- RAM Configuration: 128MB
- Cost by 100ms:  $0,0000002083
- Cost by 1ms: $0,0000000020830

2. State Machine execution graph results:
- Size: 128MB
- Time: 366ms
- Cost: 0,00000083$
![image](https://user-images.githubusercontent.com/10140897/80043741-d8af0900-8502-11ea-95cd-54175a39e7c8.png)

I guess cost is incorrect because...

**Cost with Lambda Pricing (EU-Ireland)**: 366ms * $0,0000000020830 cost/ms = **$0,0000007623780**

Also with other RAM configurations the comparation with my calculations fails...

I don't know if I'm doing smth wrong...It was only a doubt during my researching about lambda performance. 👍 

Thank you in advance!

**Comment by micprie** [comment]
Same here, minCost for eu-central-1 (Frankfurt) is 0,0000002083.
The process.env variable of minCost is set to 0,000000208.
With my tested lambda the result for bestCost is at 512 mb. But when calculating by my self the lambda would run cheaper at 2048mb...

**Comment by alexcasalboni** [comment]
Hi @Sojer23 @micprie thanks for reporting this!

> Cost with Lambda Pricing (EU-Ireland): 366ms * $0,0000000020830 cost/ms = $0,0000007623780

This calculation is actually incorrect because even if your execution time is only 366ms you will be charged for 400ms. That's what you should consider when optimizing for cost (and that's what appears in the charts). Does it make sense?

I am aware that the current implementation does not take into account different regional prices. The currently used base price for 128MB is `$0.000000208`. And you're right, it should be `$0.0000002083` for most regions. Sorry about this inaccuracy, I'm going to fix it asap.

On the other hand, do you think it's worth considering different regional prices? My initial assumption is that all that matter is the cost/performance pattern, which should stay the same even if the absolute number is slightly different (for example, the price in Hong Kong is 37% higher but it's all proportional so the optimal power configuration shouldn't change).

> With my tested lambda the result for bestCost is at 512 mb. But when calculating by my self the lambda would run cheaper at 2048mb...

@micprie can you please clarify how you calculated it yourself? As mentioned above, even if the base price is wrong, it should bring to the same optimal value.

**Comment by micprie** [comment]
Hey, thanks for your answer and sorry for giving only that sparse information...
I can't find the specific diagram where this occured :(
I calculated it by taking the prices per GB from https://aws.amazon.com/de/lambda/pricing/ multiplied by the taken time for the lambda run per 100ms. But i'm not sure at the moment if i did the round up to full 100ms...

I've updated the base cost locally and i'am fine with that now.
Thank you very much for this great tool :)

**Comment by alexcasalboni** [comment]
Ok cool, thanks for sharing :) Please keep us posted if you find any inconsistency again. I'm going to merge the PR #76 and update the SAR app so the numbers are correct for everyone.

@Sojer23 let me know if the comments above make sense. I'm going to open another issue to fix the regional base price, eventually.

**Comment by alexcasalboni** [comment]
@Sojer23 by inspecting the state machine execution you'll find the only aggregated stats (average execution time and cost). If you want the exact numbers for each individual invocation you'll find them in CloudWatch, which is what the state machine uses for the averages computation. 

For now I'm going to close this issue.

I'm going to merge #76 and evaluate what kind of work needs to be done for #77.

Thank you both!
